import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  sidebar: [
    { type: "autogenerated", dirName: "." },
    {
      type: "link",
      label: "Arcade", // The link label
      href: "/arcade", // The external URL
    },
  ],
};

export default sidebars;
