name: Static Analysis

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  static-analysis:
    name: "Lint and Type-check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.2.0
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: 18
      - name: Install dependencies
        run: pnpm install
      - name: Build library
        run: pnpm run build:lib
      - name: Type Check
        run: pnpm run typecheck
      - name: Lint
        run: pnpm run lint
