name: Static Analysis

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  static-analysis:
    name: 'Lint and Type-check'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build library
        run: yarn build:lib
      - name: Type Check
        run: yarn typecheck
      - name: Lint
        run: yarn lint
