name: Unit Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.2.0
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: 18
      - name: Install dependencies
        run: pnpm install
      - name: Unit Test
        run: pnpm run test
